[versions]
android-gradle-plugin = "8.2.1"
kotlin = "1.9.10"
androidx-appcompat = "1.6.1"
androidx-material = "1.11.0"
androidx-activity = "1.8.2"
androidx-constraintlayout = "2.1.4"
junit = "4.13.2"
ext-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-material = { module = "com.google.android.material:material", version = "1.11.0" }
androidx-activity = { module = "androidx.activity:activity", version = "1.8.2" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
junit = { module = "junit:junit", version = "4.13.2" }
ext-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
